/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import com.jechm.ejerciciosintecap.ejerciciomenu.pedido;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author eyuman
 */
public class Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gProductos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnHamburguesa = new javax.swing.JButton();
        btnTaco = new javax.swing.JButton();
        btnShuko = new javax.swing.JButton();
        btnBebida = new javax.swing.JButton();
        btnPostre = new javax.swing.JButton();
        btnAcompaniamiento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        producto1 = new javax.swing.JRadioButton();
        producto2 = new javax.swing.JRadioButton();
        producto3 = new javax.swing.JRadioButton();
        precio1 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        precio3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        extra1 = new javax.swing.JCheckBox();
        extra2 = new javax.swing.JCheckBox();
        extra3 = new javax.swing.JCheckBox();
        precioExtra1 = new javax.swing.JLabel();
        precioExtra2 = new javax.swing.JLabel();
        precioExtra3 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        cantidad = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        verPedido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Taco Taco no Mi - Menu");
        setBackground(new java.awt.Color(0, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setLocation(new java.awt.Point(150, 80));

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        btnHamburguesa.setText("Hamburguesas");
        btnHamburguesa.addActionListener(this::btnHamburguesaActionPerformed);

        btnTaco.setText("Tacos");
        btnTaco.addActionListener(this::btnTacoActionPerformed);

        btnShuko.setText("Shukos");
        btnShuko.addActionListener(this::btnShukoActionPerformed);

        btnBebida.setText("Bebidas");
        btnBebida.addActionListener(this::btnBebidaActionPerformed);

        btnPostre.setText("Postres");
        btnPostre.addActionListener(this::btnPostreActionPerformed);

        btnAcompaniamiento.setText("Acompañamientos");
        btnAcompaniamiento.addActionListener(this::btnAcompaniamientoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAcompaniamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPostre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShuko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHamburguesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnHamburguesa)
                .addGap(18, 18, 18)
                .addComponent(btnTaco)
                .addGap(18, 18, 18)
                .addComponent(btnShuko)
                .addGap(18, 18, 18)
                .addComponent(btnBebida)
                .addGap(18, 18, 18)
                .addComponent(btnPostre)
                .addGap(18, 18, 18)
                .addComponent(btnAcompaniamiento)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));

        jToggleButton1.setText("CANCELAR PEDIDO");

        jToggleButton2.setText("IMPRIMIR RECIBO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addGap(49, 49, 49))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        gProductos.add(producto1);
        producto1.setText("Hamburguesa Normal");

        gProductos.add(producto2);
        producto2.setText("Quesoburguesa");

        gProductos.add(producto3);
        producto3.setText("Hamburguesa doble");

        precio1.setText("Q 20.00");

        precio2.setText("Q 25.00");

        precio3.setText("Q 30.00");

        jLabel3.setText("Cantidad");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        extra1.setText("Queso");

        extra2.setText("Tocino");

        extra3.setText("Carne");

        precioExtra1.setText("Q 5.00");

        precioExtra2.setText("Q 8.00");

        precioExtra3.setText("Q 10.00");

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("HAMBURGUESAS");

        cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        cantidad.setMinimumSize(new java.awt.Dimension(70, 22));
        cantidad.setPreferredSize(new java.awt.Dimension(70, 22));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(producto3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(producto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(precio3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(precio2)
                                                    .addComponent(precio1)))
                                            .addComponent(producto1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(extra2)
                                            .addComponent(extra1)
                                            .addComponent(precioExtra3)
                                            .addComponent(extra3)
                                            .addComponent(precioExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(precioExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(producto1)
                    .addComponent(extra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio1)
                    .addComponent(precioExtra1))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto2)
                    .addComponent(extra2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio2)
                    .addComponent(precioExtra2))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto3)
                    .addComponent(extra3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio3)
                    .addComponent(precioExtra3))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addGap(11, 11, 11))
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));

        verPedido.setEditable(false);
        verPedido.setColumns(20);
        verPedido.setRows(5);
        jScrollPane1.setViewportView(verPedido);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public pedido miPedido = new pedido();

    private ArrayList<String> listaExtras = new ArrayList<>();
    private ArrayList<Integer> listapreciosExtras = new ArrayList<>();

    private final String[] hamburguesa = {"Hamburguesa Normal", "Quesoburguesa", "Hamburguesa doble"};
    private final int[] preciosHamburguesa = {20, 25, 30};
    private final String[] extrasHamburguesa = {"Queso", "Tocino", "Carne"};
    private final int[] preciosExtraHamburgesa = {5, 8, 10};

    private final String[] tacos = {"Tacos De Birria", "Tacos Al pastor", "Tacos De Lengua"};
    private final int[] preciosTacos = {25, 20, 20};
    private final String[] extrasTacos = {"Queso", "Salsa", "Carne"};
    private final int[] preciosExtraTacos = {5, 5, 10};

    private final String[] shukos = {"De Chorizo", "De Longaniza", "De Salchicha"};
    private final int[] preciosShukos = {12, 15, 10};
    private final String[] extrasShukos = {"Chorizo", "Longaniza", "Salchicha"};
    private final int[] preciosExtraShukos = {4, 5, 3};

    private final String[] bebidas = {"Coca Cola", "Café", "Agua Pura"};
    private final int[] precioBebidas = {12, 8, 5};

    private final String[] postres = {"CheeseCake", "Tres Leches", "Flan"};
    private final int[] precioPostres = {17, 17, 10};

    private final String[] acompaniamientos = {"Papas Fritas", "Yuca Frita", "Nachos con Carne"};
    private final int[] precioAcompaniamientos = {15, 15, 20};

    private String[] menuProductos = hamburguesa;
    private String[] menuExtras = extrasHamburguesa;
    private int[] precioProductos = preciosHamburguesa;
    private int[] precioExtras = preciosExtraHamburgesa;

    private void btnBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidaActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("BEBIDAS");
        cambiarMenu(bebidas, precioBebidas);

    }//GEN-LAST:event_btnBebidaActionPerformed


    private void btnHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("HAMBURGUESAS");
        cambiarMenu(hamburguesa, preciosHamburguesa, extrasHamburguesa, preciosExtraHamburgesa);

    }//GEN-LAST:event_btnHamburguesaActionPerformed

    private void btnTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacoActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("TACOS");
        cambiarMenu(tacos, preciosTacos, extrasTacos, preciosExtraTacos);
    }//GEN-LAST:event_btnTacoActionPerformed

    private void btnShukoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShukoActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("SHUKOS");
        cambiarMenu(shukos, preciosShukos, extrasShukos, preciosExtraShukos);

    }//GEN-LAST:event_btnShukoActionPerformed

    private void btnPostreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostreActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("POSTRES");
        cambiarMenu(postres, precioPostres);
    }//GEN-LAST:event_btnPostreActionPerformed

    private void btnAcompaniamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompaniamientoActionPerformed
        // TODO add your handling code here:
        lblTitulo.setText("ACOMPAÑAMIENTOS");
        cambiarMenu(acompaniamientos, precioAcompaniamientos);
    }//GEN-LAST:event_btnAcompaniamientoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        //agregar boton
        int cantidades = (Integer) cantidad.getValue();

        listaExtras.clear();
        listapreciosExtras.clear();

        if (cantidades > 0) {
            JRadioButton[] listaProductos = {producto1, producto2, producto3};
            int indice = 0;
            for (int i = 0; i < listaProductos.length; i++) {
                if (listaProductos[i].isSelected()) {
                    indice = i;
                }

            }
            //AQUI VOY

            JCheckBox[] seleccionExtras = {extra1, extra2, extra3};
            for (int i = 0; i < seleccionExtras.length; i++) {
                if (seleccionExtras[i].isSelected()) {
                    listaExtras.add(menuExtras[i]);
                    listapreciosExtras.add(precioExtras[i]);
                }
            }

            if (listapreciosExtras.isEmpty()) {
                miPedido.agregarProducto(cantidades, menuProductos[indice], precioProductos[indice]);

            } else {
                miPedido.agregarProducto(cantidades, menuProductos[indice], precioProductos[indice], listaExtras, listapreciosExtras);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cantidad no válida, intente de nuevo");
        }

        String listaPedido = "Cant.\tProducto          \t\tPrecio U\tSub-Total";
        for (int i = 0; i < miPedido.getCantidades().size(); i++) {
            String separaPrecio = "";
            String productoActual = miPedido.getProductos().get(i).toString();
            for (int j = 0; j < 20 - productoActual.length(); j++) {
                separaPrecio = separaPrecio + " ";
            }
            if (productoActual.equals("Flan") || productoActual.equals("Café")){
                separaPrecio = separaPrecio+"\t";
            }
            separaPrecio = separaPrecio + "\tQ ";

            listaPedido = listaPedido + "\n" + miPedido.getCantidades().get(i) + "\t" + miPedido.getProductos().get(i) + separaPrecio + miPedido.getPrecios().get(i) + "\t Q " + ((Integer) miPedido.getCantidades().get(i) * (Integer) miPedido.getPrecios().get(i));
        }
        listaPedido = listaPedido + "\n---------------------------\nTotal: Q "+miPedido.getTotalAPagar();
        verPedido.setText("");
        verPedido.setText(listaPedido);
        cantidad.setValue(0);

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void asignarProductos(String[] productos, int[] precios) {
        producto1.setText(productos[0]);
        producto2.setText(productos[1]);
        producto3.setText(productos[2]);

        precio1.setText("Q " + precios[0] + ".00");
        precio2.setText("Q " + precios[1] + ".00");
        precio3.setText("Q " + precios[2] + ".00");

        menuProductos = productos;
        precioProductos = precios;
    }

    private void cambiarMenu(String[] productos, int[] precios, String[] extras, int[] preciosExtras) {
        limpiarCheckBox();
        asignarProductos(productos, precios);

        extra1.setText(extras[0]);
        extra2.setText(extras[1]);
        extra3.setText(extras[2]);
        precioExtra1.setText("Q " + preciosExtras[0] + ".00");
        precioExtra2.setText("Q " + preciosExtras[1] + ".00");
        precioExtra3.setText("Q " + preciosExtras[2] + ".00");

        conExtras();

        menuProductos = productos;
        menuExtras = extras;
        precioProductos = precios;
        precioExtras = preciosExtras;

    }

    private void cambiarMenu(String[] productos, int[] precios) {
        limpiarCheckBox();
        asignarProductos(productos, precios);
        sinExtras();

        menuProductos = productos;
        precioProductos = precios;
    }

    private void limpiarCheckBox() {
        extra1.setSelected(false);
        extra2.setSelected(false);
        extra3.setSelected(false);
    }

    private void sinExtras() {
        extra1.setVisible(false);
        extra2.setVisible(false);
        extra3.setVisible(false);
        precioExtra1.setVisible(false);
        precioExtra2.setVisible(false);
        precioExtra3.setVisible(false);

    }

    private void conExtras() {
        extra1.setVisible(true);
        extra2.setVisible(true);
        extra3.setVisible(true);
        precioExtra1.setVisible(true);
        precioExtra2.setVisible(true);
        precioExtra3.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcompaniamiento;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBebida;
    private javax.swing.JButton btnHamburguesa;
    private javax.swing.JButton btnPostre;
    private javax.swing.JButton btnShuko;
    private javax.swing.JButton btnTaco;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JCheckBox extra1;
    private javax.swing.JCheckBox extra2;
    private javax.swing.JCheckBox extra3;
    private javax.swing.ButtonGroup gProductos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel precio3;
    private javax.swing.JLabel precioExtra1;
    private javax.swing.JLabel precioExtra2;
    private javax.swing.JLabel precioExtra3;
    private javax.swing.JRadioButton producto1;
    private javax.swing.JRadioButton producto2;
    private javax.swing.JRadioButton producto3;
    private javax.swing.JTextArea verPedido;
    // End of variables declaration//GEN-END:variables
}
